import Foundation
import KoubutsuCore

/// Expected on-screen text for a test clip (generated by `Tools/make_test_clip.py`).
/// Used by fixture tests now and by the benchmark harness later.
struct ClipManifest: Decodable, Sendable {
    struct Expected: Decodable, Sendable {
        let text: String
        let box: NormalizedRect
    }

    struct Checkpoint: Decodable, Sendable {
        let id: String
        let start: Double
        let end: Double
        let expected: [Expected]

        /// A time inside the checkpoint where all expected text is fully shown.
        var sampleTime: Double { (start + end) / 2 }
    }

    let name: String
    let width: Int
    let height: Int
    let fps: Double
    let duration: Double
    let checkpoints: [Checkpoint]

    static func load(named name: String, bundle: Bundle = .main) throws -> ClipManifest {
        guard let url = bundle.url(forResource: name, withExtension: "json") else {
            throw CocoaError(.fileNoSuchFile)
        }
        return try JSONDecoder().decode(ClipManifest.self, from: Data(contentsOf: url))
    }

    func checkpoint(_ id: String) -> Checkpoint? { checkpoints.first { $0.id == id } }
}
